In [19]:
import numpy as np

In [20]:
lista = [1,2,3,4,5,6]
array = np.array(lista)
print(lista)
print(array)
print(type(lista))
print(type(array))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'list'>
<class 'numpy.ndarray'>


In [22]:
arr_zeros = np.zeros(10)
print (arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [23]:
##Matrizes
matriz_zeros = np.zeros((5,3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
##nota de alunos
lista_de_notas = [9.8,5.6,7.8,9.1,6.5]
notas = np.array(lista_de_notas)
print('Máximo', notas.max())
print('Minimo', notas.min())
print('Desvio padrão', notas.std())
print('Média', notas.mean())
print('Posição do menor', notas.argmin())
print('Posição do maior', notas.argmax())

Máximo 9.8
Minimo 5.6
Desvio padrão 1.5628179676469045
Média 7.76
Posição do menor 1
Posição do maior 0


In [40]:
lista_de_notas = input(print("Qual a lista de notas?"))
notas = [float (elemento) for elemento in lista_de_notas.split(',')]  ## converter o texto de entrada em flot, separado pela ,
notas = np.array(notas) ## Transsformar os elementos em um array --> Ou seja, lista otimizada para operações númericas
print('Máximo', notas.max())
print('Minimo', notas.min())
print('Desvio padrão', notas.std())
print('Média', notas.mean())
print('Posição do menor', notas.argmin())
print('Posição do maior', notas.argmax())

Qual a lista de notas?


None 8.9,3.2,5,9


Máximo 9.0
Minimo 3.2
Desvio padrão 2.5073641538476217
Média 6.525
Posição do menor 1
Posição do maior 3


In [43]:
is_covid_positive = np.array(['Yes','No','Yes','No','Yes','No']) ### Lista de valores
mask = (is_covid_positive =='Yes' ) ## Condição de validação se satisfas
print(mask)
is_covid_positive[mask] = 'C19' ## Substituir as condições que são true pelo valor proposto
print(is_covid_positive) ## Nova lista 

[ True False  True False  True False]
['C19' 'No' 'C19' 'No' 'C19' 'No']


In [51]:
lista_de_notas = np.array([9.8,5.6,7.8,9.1,6.5,3.2,4.9]) ### Lista de valores
mask = (lista_de_notas>= 6.0) ## Condição de validação se satisfas
print(mask)
resultado_final = np.where(mask, 'Passou', 'Reprovou') ## Aqui faz a função "Case when" do SQL
print(resultado_final)

[ True False  True  True  True False False]
['Passou' 'Reprovou' 'Passou' 'Passou' 'Passou' 'Reprovou' 'Reprovou']
